### PR TITLE
Add support for Keycloak. Implements #39

### LINKED ISSUE #39: [request] Add support for authenticating to Keycloak
## Description

Sites that are behind a [Keycloak](https://www.keycloak.org/) setup can't be scraped because the scraper currently can't authenticate to it. 

## Steps to reproduce

Try scraping a site that's behind a Keycloak setup. 

## Expected Behavior

A [competing scraper](https://github.com/meilisearch/docs-scraper/blob/f9f782259860d98d109151637f2e34b77c2fb8e6/README.md#keycloak-access-identity-and-access-management-) supports this and even includes instructions in the README on how to configure it.

It would be nice if we could have a similar functionality.

## Actual Behavior

The scraper will be redirected, and index the Keycloak site (if you configure it to) but doesn't know how to authenticate.

## Metadata

**Typesense Version**: 0.24.1

**OS**: Debian Linux

### PR DESCRIPTION
**Pull request by joostdecock**
## Change Summary
This adds support for Keycloak SSO, which closes #39 

I have also added an extra section to the README with info that I found was (too) hard to find:

- Supported authentication methods
- How to deal with some common challenges when running in Docker

If that is unwanted, I can re-submit without the README changes.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by joostdecock** [comment]
@jasonbosco sure thing:

- Submitted a PR for the docs: https://github.com/typesense/typesense-website/pull/177
- Reverted the changes to the README in this PR

**Comment by jasonbosco** [comment]
@joostdecock Thank you! I've published your updates in `typesense/docsearch-scraper:0.7.0.rc1 `. Could you give it a shot and confirm that it works as expected?

**Comment by joostdecock** [comment]
@jasonbosco it seems to be missing the dependency:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/seleuser/src/index.py", line 8, in <module>
    from keycloak.realm import KeycloakRealm
ModuleNotFoundError: No module named 'keycloak'
```

**Comment by jasonbosco** [comment]
Oops, I missed a build step. Could you try again with `typesense/docsearch-scraper:0.7.0.rc2`?

**Comment by joostdecock** [comment]
@jasonbosco Sorry for the delay, I had some unexpected health issues, but the dependency issue is fixed in `rc2` 👍

**Pull request merged**
