### PR TITLE
fix: explicit fingerprinter param in custom dupefilter

### PR DESCRIPTION
**Pull request by SheezZarR**
## Change Summary
The scraper uses `Scrapy = ">=2.2.1"` as its dependency. Recent update from 2.11.* to 2.12.1 introduced a new requirement ([see here](https://docs.scrapy.org/en/latest/news.html#deprecation-removals)): 
> RFPDupeFilter subclasses now require supporting the fingerprinter parameter in their __init__ method, introduced in Scrapy 2.7.0. ([issue 6102](https://github.com/scrapy/scrapy/issues/6102), [issue 6113](https://github.com/scrapy/scrapy/issues/6113))

Hence I updated the signature of the class `CustomDupeFilter`. The explicit return statement is due to pyright complaints. 

## PR Checklist
- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by SheezZarR** [comment]
Perhaps its best to pin down the versions in Piplock file?

**Comment by jasonbosco** [comment]
@SheezZarR Yeah good idea - mind pinning the versions as part of this PR?

**Comment by SheezZarR** [comment]
@jasonbosco i have updated the file.  
However two tests are failing but I believe its unrelated..? 
```
FAILED scraper/src/tests/typesense_helper/commit_tmp_test.py::test_create_tmp_collection - AssertionError: assert {'default_sor...lection', ...} == {'default_sor...lection', ...}
FAILED scraper/src/tests/typesense_helper/commit_tmp_test.py::test_create_tmp_collection_already_exists - typesense.exceptions.ObjectAlreadyExists: [Errno 409] A collection with name `collection` already exists.
```

I am using local typesense server of version 0.25.2-1. ([here](https://aur.archlinux.org/packages/typesense-bin))

**Comment by tharropoulos** [comment]
> I am using local typesense server of version 0.25.2-1. ([here](https://aur.archlinux.org/packages/typesense-bin))

Since I'm also using an Arch-based distribution myself, I'd suggest looking into using our [docker](https://hub.docker.com/r/typesense/typesense/) image for local development, as the AUR package isn't actively being maintained from the looks of it

**Comment by SheezZarR** [comment]
@tharropoulos thanks a lot for helping out!
I have seen that the AUR package is a bit obsolete, colleagues have strong opinions on docker, so we are not using it atm :) Will try to fix the lint issues and update the PR.

**Comment by jasonbosco** [comment]
@SheezZarR I wonder if the linting rules got updated because the linter was not pinned. If the failing lint checks are from code that wasn't modified in this PR, feel free to pin the linter to the previous version as well.

**Comment by SheezZarR** [comment]
@jasonbosco thanks I was a bit clumsy on this one. Hope the update will fix the problem

**Comment by SheezZarR** [comment]
@jasonbosco CI/CD keeps failing in my fork localy. I'll report back when to run the Action in here

**Comment by SheezZarR** [comment]
@jasonbosco [looks green to me](https://github.com/SheezZarR/typesense-docsearch-scraper/actions/runs/12223620821)  

Some weird shenanigans with the lock-file.

**Review by jasonbosco — APPROVED** [review]

**Comment by jasonbosco** [comment]
Thank you again for the PR @SheezZarR!

**Comment by jasonbosco** [comment]
The changes are now in `typesense/docsearch-scraper:0.12.0.rc2`. Could you give it a shot now?

**Comment by SheezZarR** [comment]
@jasonbosco yah, the scrapper works now! :+1:

**Pull request merged**
